; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; [platformio]
; registry_url =  https://mirrors.ustc.edu.cn/platformio/registry
; lib_ldf_mode = deep+
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_encoding = utf-8      ; 强制使用UTF-8编码
monitor_filters = send_on_enter, default 
monitor_raw = no      
lib_deps = 
    ; MPU6050 主分支源码包（替代404的0.6.0 tag包，功能兼容）
    https://github.com/ElectronicCats/mpu6050.git
    ; ADS1X15 2.5.0 有效压缩包URL（验证可访问）
    https://xget.xi-xu.me/gh/adafruit/Adafruit_BusIO/archive/refs/heads/master.zip
    https://github.com/adafruit/Adafruit_ADS1X15.git
    ; ElectronicCats/MPU6050 @ ^1.0.0
    ; ADS1115 库（自动拉取依赖的BusIO）
    ; adafruit/Adafruit ADS1X15 @ ^2.5.0
    ; https://github.com/adafruit/Adafruit_BusIO.git
	SPI@^2.0.0
    ; 使用ADS1115需要开启以上两个仓库